defmodule PhoenixKitComments.Integration.BackdatedCommentsTest do
  @moduledoc """
  PR #36 added `:inserted_at` backdating to `create_comment/4` for
  server-created anchor comments, but shipped with no coverage — the only
  proof it worked was manual verification in a host app. These pin the
  contract: a real `DateTime` wins over autogeneration, and anything else
  (including a plain client-shaped map) is silently ignored rather than
  raising or leaking through.
  """
  use PhoenixKitComments.DataCase, async: true

  alias PhoenixKitComments.Test.Repo

  setup do
    {:ok, user: user_fixture()}
  end

  describe "backdating via :inserted_at" do
    test "a real DateTime overrides the autogenerated timestamp", %{user: user} do
      backdate = DateTime.new!(~D[2020-01-01], ~T[12:00:00])

      {:ok, comment} =
        PhoenixKitComments.create_comment(
          "test_resource",
          Ecto.UUID.generate(),
          user.uuid,
          %{content: "anchor comment", inserted_at: backdate}
        )

      assert DateTime.compare(comment.inserted_at, backdate) == :eq

      reloaded = Repo.get(PhoenixKitComments.Comment, comment.uuid)
      assert DateTime.compare(reloaded.inserted_at, backdate) == :eq

      # updated_at stays honest — it records when the row was actually
      # written, not the backdated moment it claims to anchor.
      assert DateTime.diff(DateTime.utc_now(), reloaded.updated_at, :second) < 5
    end

    test "sub-second precision is truncated to match the column", %{user: user} do
      backdate = DateTime.new!(~D[2020-01-01], ~T[12:00:00.123456])

      {:ok, comment} =
        PhoenixKitComments.create_comment(
          "test_resource",
          Ecto.UUID.generate(),
          user.uuid,
          %{content: "anchor comment", inserted_at: backdate}
        )

      assert comment.inserted_at.microsecond == {0, 0}
    end

    test "a non-DateTime value is ignored, not cast or raised on", %{user: user} do
      {:ok, comment} =
        PhoenixKitComments.create_comment(
          "test_resource",
          Ecto.UUID.generate(),
          user.uuid,
          %{content: "not backdated", inserted_at: "2020-01-01T12:00:00Z"}
        )

      assert DateTime.diff(DateTime.utc_now(), comment.inserted_at, :second) < 5
    end

    test "omitting :inserted_at keeps the normal autogenerated timestamp", %{user: user} do
      {:ok, comment} =
        PhoenixKitComments.create_comment(
          "test_resource",
          Ecto.UUID.generate(),
          user.uuid,
          %{content: "normal comment"}
        )

      assert DateTime.diff(DateTime.utc_now(), comment.inserted_at, :second) < 5
    end
  end
end
